name: Build + Lint

on: push

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env
          echo 'CHOCOLATEY_API_KEY=${{secrets.CHOCOLATEY_API_KEY}}' >> .release-env

      - name: GoReleaser
        run: make choco-cross
        if: startsWith(github.ref, 'refs/tags/')

  lint:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: README.md
          debug: true
          fail_on_error: true
          reporter: github-check
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
